<?php
$payments = $this->payments;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Payment Method</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<div class="body">
		<div class="box">
			Manage Payment Method
		</div>
		<div class="link">
			<a href="<?php echo $this->getUrl('add', null, [], true);?>">Add Payment Method</a>
		</div>
	</div>
	<table cellpadding="40%" border="30px">
		<?php if (!$payments): ?>
		<tr>
			<td colspan="7" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr bgcolor="brown">
			<th>Payment Method Id</th>
			<th>Name</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($payments as $payment) : ?>
		<tr bgcolor="skyblue">
			<td><?php echo $payment->payment_method_id; ?></td>
			<td><?php echo $payment->name; ?></td>
			<td><?php echo $payment->getStatusText(); ?></td>
			<td><?php echo $payment->created_at; ?></td>
			<td><?php echo $payment->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $payment->payment_method_id], true);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $payment->payment_method_id], true);?>">DELETE</a></td>
		</tr>
	<?php endforeach; ?>
	<?php endif; ?>
	</table>
</body>
</html>