<div class="head">
	<div class="button">
		<a href="index.php?c=admin&a=grid">Admin</a>
	</div>
	<div class="button">
		<a href="index.php?c=product&a=grid">Product</a>
	</div>
	<div class="button">
		<a href="index.php?c=category&a=grid">Category</a>
	</div>
	<div class="button">
		<a href="index.php?c=customer&a=grid">Customer</a>
	</div>
	<div class="button">
		<a href="index.php?c=vendor&a=grid">Vendor</a>
	</div>
	<div class="button">
		<a href="index.php?c=salesman&a=grid">Salesman</a>
	</div>
	<div class="button">
		<a href="index.php?c=shipping&a=grid">Shipping Method</a>
	</div>
	<div class="button">
		<a href="index.php?c=payment&a=grid">Payment Method</a>
	</div>
</div>
