<style type="text/css">
	.success{
		background-color: red;
		color: white;
		text-align: center;
	}
	.failure{
		background-color: orangered;
		color: white;
		text-align: center;
	}
	.notice{
		background-color: pink;
		color: white;
		text-align: center;
	}
</style>
<?php
$messageObject = Ccc::getModel('Core_Message');
$messageObject->getSession()->start();
if (isset($_SESSION['message'])) {
	$messages = $messageObject->getMessages();
	foreach ($messages as $type => $message) {
		echo "<h3 class ='" . $type . "' >" . $message . "</h3>";
	}
	$messageObject->clearMessage();
}
?>