<?php
$customers = $this->customers;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Customer</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<div class="body">
		<div class="box">
			Manage Customers
		</div>
		<div class="link">
			<a href="<?php echo $this->getUrl('add', null, [], true);?>">Add Customer</a>
		</div>
	</div>
	<table width="100%" cellpadding="30%" border="20px">
		<?php if (!$customers): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr bgcolor="brown">
			<th>Customer Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>email</th>
			<th>Gender</th>
			<th>Mobile</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($customers as $customer) : ?>
		<tr bgcolor="skyblue">
			<td><?php echo $customer->customer_id; ?></td>
			<td><?php echo $customer->first_name; ?></td>
			<td><?php echo $customer->last_name; ?></td>
			<td><?php echo $customer->email; ?></td>
			<td><?php echo $customer->getGenderText(); ?></td>
			<td><?php echo $customer->mobile; ?></td>
			<td><?php echo $customer->getStatusText(); ?></td>
			<td><?php echo $customer->created_at; ?></td>
			<td><?php echo $customer->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $customer->customer_id]);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $customer->customer_id]);?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>