<?php
$shippings = $this->shippings;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Shipping Method</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<div class="body">
		<div class="box">
			Manage Shipping Method
		</div>
		<div class="link">
			<a href="<?php echo $this->getUrl('add', null , [], true);?>">Add Shipping Method</a>
		</div>
	</div>
	<table width="100%" cellpadding="30%" border="20px">
		<?php if (!$shippings): ?>
		<tr>
			<td colspan="11" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr bgcolor="brown">
			<th>Shipping Method Id</th>
			<th>Name</th>
			<th>Amount</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($shippings as $shipping) : ?>
		<tr bgcolor="skyblue">
			<td><?php echo $shipping->shipping_method_id; ?></td>
			<td><?php echo $shipping->name; ?></td>
			<td><?php echo $shipping->amount; ?></td>
			<td><?php echo $shipping->getStatusText(); ?></td>
			<td><?php echo $shipping->created_at; ?></td>
			<td><?php echo $shipping->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $shipping->shipping_method_id]);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $shipping->shipping_method_id]);?>">DELETE</a></td>
		</tr>
	<?php endforeach; ?>
	<?php endif; ?>
	</table>
</body>
</html>