<?php $product = $this->product; ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Product</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<form action="<?php echo $this->getUrl('save'); ?>" method="post">
		<div class="add">
			<div>Product</div>
			<div class="cancel">
				<button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
			</div>
			<div class="submit">
				<button type="submit">Submit</button>
			</div>
		</div>
		<div>Product Information</div>
		<table>
			<tr>
				<td>Name</td>
				<td><input type="text" name="product[name]" value="<?php echo $product->name; ?>"></td>
			</tr>
			<tr>
				<td>SKU</td>
				<td><input type="text" name="product[sku]" value="<?php echo $product->sku; ?>"></td>
			</tr>
			<tr>
				<td>Cost</td>
				<td><input type="text" name="product[cost]" value="<?php echo $product->cost; ?>"></td>
			</tr>
			<tr>
				<td>Price</td>
				<td><input type="text" name="product[price]" value="<?php echo $product->price; ?>"></td>
			</tr>
			<tr>
				<td>Quantity</td>
				<td><input type="text" name="product[quantity]" value="<?php echo $product->quantity; ?>"></td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="product[status]">
						<?php foreach ($product->getStatusOptions() as $key => $value) : ?>
						<?php $selected = ($key == $product->getStatus()) ? "selected" : ''; ?>
						<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
		</table>
	</form>
</body>
</html>