<?php
$products = $this->products; 
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Product</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<div class="body">
		<div class="box" >
			Manage Products
		</div>
		<div class="link">
			<a href="<?php echo $this->getUrl('add', null , [], true);?>">Add Product</a>
		</div>
	</div>
	<table cellpadding="40%" border="20px">
		<?php if (!$products): ?>
		<tr>
			<td colspan="5" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr bgcolor="brown">
			<th>Product_id</th>
			<th>Name</th>
			<th>SKU</th>
			<th>Cost</th>
			<th>Price</th>
			<th>Quantity</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>MEDIA</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($products as $product) : ?>
		<tr bgcolor="skyblue">
			<td><?php echo $product->product_id; ?></td>
			<td><?php echo $product->name; ?></td>
			<td><?php echo $product->sku; ?></td>
			<td><?php echo $product->cost; ?></td>
			<td><?php echo $product->price; ?></td>
			<td><?php echo $product->quantity; ?></td>
			<td><?php echo $product->getStatusText(); ?></td>
			<td><?php echo $product->created_at; ?></td>
			<td><?php echo $product->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl(null, 'product_media', ['id'=> $product->product_id], true);?>">Media</a></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $product->product_id], true);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $product->product_id], true);?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>