<?php
$salesmen = $this->salesmen;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Salesman</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<div class="body">
		<div class="box">
			Manage Salesman
		</div>
		<div class="link">
			<a href="<?php echo $this->getUrl('add', null, [], true);?>">Add Salesman</a>
		</div>
	</div>
	<table width="100%" cellpadding="30%" border="20px">
		<?php if (!$salesmen): ?>
		<tr>
			<td colspan="11" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr bgcolor="brown">
			<th>Salesman Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>email</th>
			<th>Gender</th>
			<th>Mobile</th>
			<th>Status</th>
			<th>Price</th>
			<th>Company</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($salesmen as $salesman) : ?>
		<tr bgcolor="skyblue">
			<td><?php echo $salesman->salesman_id; ?></td>
			<td><?php echo $salesman->first_name; ?></td>
			<td><?php echo $salesman->last_name; ?></td>
			<td><?php echo $salesman->email; ?></td>
			<td><?php echo $salesman->getGenderText(); ?></td>
			<td><?php echo $salesman->mobile; ?></td>
			<td><?php echo $salesman->getStatusText(); ?></td>
			<td><a href="<?php echo $this->getUrl('grid', 'salesman_price', ['id'=> $salesman->salesman_id]);?>">PRICE</a></td>
			<td><?php echo $salesman->company; ?></td>
			<td><?php echo $salesman->created_at; ?></td>
			<td><?php echo $salesman->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $salesman->salesman_id]);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $salesman->salesman_id]);?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>